### ISSUE TITLE
man link with dot is broken

### ISSUE THREAD

**Issue by straight-shoota** [postmodern/kramdown-man#15]
A man link containing a dot seems to be broken:

```md
See [shard.yml](man:shard.yml(5)) for more information.
```
```roff
See
.BR shard for more
information\.
```

**Comment by postmodern** [comment]
That would be due to the overly precise regex: https://github.com/postmodern/kramdown-man/blob/0d5ee35476ead5b2ab1be0e8241581345b4d579e/lib/kramdown/converter/man.rb#L773

This regex matches `man:page.num` style URIs, which FireFox actually honors and will open them in the [yelp]() man page browser.

Appears that `man shard.yml` works though, so I'll expand the regex.
